# Generated by Django 6.0.4 on 2026-04-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
